/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Add: typeof import('./src/components/home/goods/list/children/Add.vue')['default']
    Breadcrumb: typeof import('./src/components/content/breadcrumb/Breadcrumb.vue')['default']
    Cate: typeof import('./src/components/home/goods/cate/Cate.vue')['default']
    Home: typeof import('./src/components/home/Home.vue')['default']
    IEpLock: typeof import('~icons/ep/lock')['default']
    IEpock: typeof import('~icons/ep/ock')['default']
    IEpOck: typeof import('~icons/ep/ock')['default']
    IEpSearch: typeof import('~icons/ep/search')['default']
    List: typeof import('./src/components/home/goods/list/List.vue')['default']
    Login: typeof import('./src/components/Login.vue')['default']
    Order: typeof import('./src/components/home/order/Order.vue')['default']
    Params: typeof import('./src/components/home/goods/params/Params.vue')['default']
    Report: typeof import('./src/components/home/report/Report.vue')['default']
    Rights: typeof import('./src/components/home/power/rights/Rights.vue')['default']
    Roles: typeof import('./src/components/home/power/roles/Roles.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Users: typeof import('./src/components/home/users/Users.vue')['default']
    Welcome: typeof import('./src/components/home/welcome/Welcome.vue')['default']
  }
}
