/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Add: typeof import('./components/home/goods/list/children/Add.vue')['default']
    Breadcrumb: typeof import('./components/content/breadcrumb/Breadcrumb.vue')['default']
    Cate: typeof import('./components/home/goods/cate/Cate.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    Home: typeof import('./components/home/Home.vue')['default']
    List: typeof import('./components/home/goods/list/List.vue')['default']
    Login: typeof import('./components/Login.vue')['default']
    Order: typeof import('./components/home/order/Order.vue')['default']
    Params: typeof import('./components/home/goods/params/Params.vue')['default']
    Report: typeof import('./components/home/report/Report.vue')['default']
    Rights: typeof import('./components/home/power/rights/Rights.vue')['default']
    Roles: typeof import('./components/home/power/roles/Roles.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Users: typeof import('./components/home/users/Users.vue')['default']
    Welcome: typeof import('./components/home/welcome/Welcome.vue')['default']
  }
}
